org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.2)
neo_version=21.1.92
neo_version_range=[21.1.0,21.2.0)
loader_version_range=[4,)

architectury_version=13.0.8
cloth_config_version=15.0.140
rei_version=16.0.788

jei_version=19.16.4.164

mod_id=resourcestrees
mod_name=ResourcesTrees
mod_license=All Rights Reserved
mod_version=1.0.3+mc1.21.1-neoforge
mod_group_id=com.coolerpromc.resourcestrees
mod_authors=CoolerProMC
mod_description=
