org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05
minecraft_version=1.21.10
minecraft_version_range=[1.21.9, 1.21.11)
neo_version=21.10.0-beta

architectury_version=17.0.8
cloth_config_version=19.0.147
rei_version=20.0.810

jei_version=26.0.0.1

mod_id=resourcestrees
mod_name=ResourcesTrees
mod_license=All Rights Reserved
mod_version=1.6.2+mc1.21.10-neoforge
mod_group_id=com.coolerpromc
mod_authors=CoolerProMC
mod_description=
